### ISSUE TITLE
magrittr to native pipe

### ISSUE THREAD

**Issue by JoFrhwld** [tjmahr/readtextgrid#5]
Converting `%>%` to `|>` could result in some speedup. [https://michaelbarrowman.co.uk/post/the-new-base-pipe/](https://michaelbarrowman.co.uk/post/the-new-base-pipe/)

The two aren't fully interchangeable, so any substitution would have to double check

- the magrittr `.` placeholder isn't being used.
- the right hand side uses the function `fn()` rather than just its name `fn`

**Comment by tjmahr** [comment]
Not worried about speed, but it's nice losing the dependency and getting a cleaner traceback. 

A couple notes:

I would need to add to DESCRIPTION

```
Depends: R (>= 4.1.0)
```

and update the README to use native pipe while we're at it.
